### ISSUE TITLE
Bind `run_multiple_get_results`

### ISSUE THREAD

**Issue by IsaccBarker** [UofUEpiBio/epiworldpy#33]
Bind the functions:
- [ ] `run_multiple_get_results`

**Comment by IsaccBarker** [comment]
@gvegayon Is there anything that requires the CSV files to be dumped to disk in the Saver? It seems the way you're supposed to interact with them is through the opaque `run_multiple_get_results` interface. I think it would be more stable and less prone-to-breakage to store the results in the Saver object itself instead of to temporary files. Is this something you'd be willing to deviate from the R bindings on?

**Comment by gvegayon** [comment]
The problem with the data generated by run_multiple is that it can be very big. Furthermore, in simulation studies, it is often the case that we dump results to disk instead of keeping them in memory as if the software fails, we still get to see some of the results. I rather stay with the existing approach.
